# Generated by Django 4.2.6 on 2023-10-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_main.subject'),
        ),
    ]
